<?php
$db['store_statis']=array(
	'columns'=>array(
		'statis_id'=>array(
			'type'=>'number',
			'required' => true,
			'pkey' => true,
			'extra' => 'auto_increment',
			'editable' => false,
			'label' => app::get('storelist')->_('编号'),
			'comment' => app::get('storelist')->_('编号'),
		),
			'store_id'=>array(
				'type'=>'number',
				'required' => true,
				'label' => app::get('storelist')->_('店铺ID'),
				'width' => 110,
				'editable' => false,
				'in_list' => true,
				'default_in_list' => true,
				'comment' => app::get('storelist')->_('店铺ID'),
		),
			'month_volume'=>array(
				'type'=>'money',
				'required' => true,
				'label' => app::get('storelist')->_('月度销售总金额'),
				'width' => 110,
				'default'=>'0',
				'editable' => false,
				'in_list' => true,
				'default_in_list' => true,
				'comment' => app::get('storelist')->_('月度销售总金额'),
			),
			'create_time'=>array(
				'type'=>'time',
				'required' => true,
				'label' => app::get('storelist')->_('创建时间'),
				'width' => 110,
				'editable' => false,
				'in_list' => true,
				'default_in_list' => true,
				'comment' => app::get('storelist')->_('创建时间'),
			),
			'name'=>array(
				'type'=>'varchar(50)',
				//'required' => true,
				'label' => app::get('storelist')->_('等级名称'),
				'width' => 110,
				'editable' => false,
				'in_list' => true,
				'default_in_list' => true,
				'comment' => app::get('storelist')->_('等级名称'),
			),
	),
		'engine' => 'innodb',
		'version' => '$Rev: 40912 $',
		'comment' => app::get('storelist')->_('门店主评级表'),
);
?>